# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /#about
    weight: 1
  - name: Research Interests
    url: /#projects
    weight: 2
  - name: Publications
    url: /#publications
    weight: 3
  - name: Awards & Certifications
    url: /#accomplishments
    weight: 4
  - name: CV
    url: uploads/CV.pdf
    weight: 5
  - name: Contact
    url: /#contact
    weight: 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
